// Code generated by scripts/generate.mjs. DO NOT EDIT.
package noxmcp

const BridgeProtocolVersion = "2.0"
const DefaultTimeoutMS = 20000
const MaxPayloadBytes = 2097152
const MaxInFlightRequests = 32
