import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
const { z } = createRequire(new URL('../typescript/package.json', import.meta.url))('zod');
import * as contract from '../typescript/dist/contract.js';
const root = fileURLToPath(new URL('../', import.meta.url));
const check = process.argv.includes('--check');
function emit(path, content) {
  if (check) { if (readFileSync(root + path, 'utf8').replaceAll('\r\n', '\n') !== content) throw new Error(`Regenerate ${path}`); }
  else { mkdirSync(root + path.slice(0, path.lastIndexOf('/')), { recursive: true }); writeFileSync(root + path, content); }
}
const d = contract.defaults;
emit('contracts/defaults.json', JSON.stringify(d, null, 2) + '\n');
emit('rust/src/defaults.rs', `// Generated by scripts/generate.mjs.\npub const BRIDGE_PROTOCOL_VERSION: &str = "${d.bridgeProtocolVersion}";\npub const DEFAULT_TIMEOUT_MS: u64 = ${d.requestTimeoutMs};\npub const MAX_PAYLOAD_BYTES: usize = ${d.maxPayloadBytes};\npub const MAX_IN_FLIGHT_REQUESTS: usize = ${d.maxInFlightRequests};\n`);
emit('go/defaults.go', `// Code generated by scripts/generate.mjs. DO NOT EDIT.\npackage noxmcp\n\nconst BridgeProtocolVersion = "${d.bridgeProtocolVersion}"\nconst DefaultTimeoutMS = ${d.requestTimeoutMs}\nconst MaxPayloadBytes = ${d.maxPayloadBytes}\nconst MaxInFlightRequests = ${d.maxInFlightRequests}\n`);
for (const [name, schema] of Object.entries({ request: contract.bridgeRequestSchema, response: contract.bridgeResponseSchema, server: contract.serverBridgeMessageSchema, desktop: contract.desktopBridgeMessageSchema, error: contract.bridgeErrorSchema, manifest: contract.toolManifestSchema })) {
  const json = JSON.stringify(z.toJSONSchema(schema, { target: 'draft-7', io: 'input' }), null, 2) + '\n';
  emit(`contracts/${name}.schema.json`, json);
  emit(`go/contracts/${name}.schema.json`, json);
  emit(`rust/contracts/${name}.schema.json`, json);
}
const fixtures = JSON.stringify(JSON.parse(readFileSync(root + 'conformance/cases.json','utf8')), null, 2) + '\n';
emit('go/contracts/cases.json', fixtures);
emit('rust/contracts/cases.json', fixtures);
